---
title: "Press"
---
<body>
Here you can find a list of my academic and as non-academic publications and presentations, followed by useful resources on hand papermaking written by other authors.

<br>

### Academic publications
Reid, J.L., Fagan, M.E., Cattau, M.E., Lucas, J., & Zahawi, R.A. (2019).  [The ephemerality of regenerating secondary forests in Costa Rica](files/Reid et al. 2019).  *Conservation Letters* **12**(2), 12607.  

Lucas, J.  (2014).  [Demographic Survey of the Sohisika (Schizolaena tampoketsana) at Ankafobe, Madagascar.](http://digitalcollections.sit.edu/isp_collection/1763)  Independent Study Project (ISP) Collection.  Paper 1763.  

Millard, J. T., Chuang, E., Lucas, J. S., Nagy, E. E., & Davis, G. T. (2013). [Case-Study Investigation of Equine Maternity via PCR-RFLP: A Biochemistry Laboratory Experiment.](files/Millard et al. 2013.pdf) *Journal of Chemical Education*, **90**(11), 1518-1521.

<br>

### Non-academic publications
Lucas, J.  (2020).  "[Paperfolders Need Lots of Fiber: The Ethnobotany of Origami.](files/lucas_ethnobotany.pdf)"  *The Paper* **132**, p. 24-25.

Missouri Botanical Garden.  (2019).  [Leafing Through History: Plants that Make Paper.](files/LTH_web.pdf).  St. Louis, MO., USA.

<br>

### Presentations
9 February 2020.  "[The Ethnobotany of Origami.](https://www.youtube.com/watch?v=ReUyVmmkLdM)"  Conference for Creators, Zaragoza, Spain.

13 Sep 2019.  “The Ethnobotany of Origami.”  Pacific Coast Origami Conference, Portland, OR., USA.  

13 May 2019.  “Following the Paper Trail: Unfolding the Ecology of Origami.”  Science Distilled, Urban Chestnut Brewing Co., St. Louis, MO.  

<br>

### Further reading
Boesi, A. (2016).  “[Paper Plants in the Tibetan World: A Preliminary Study.](files/Boesi 2016.pdf)” In H. Diemberger, F.-K. Ehrhard, & P. Kornicki (Eds.), *Tibetan Printing: Comparison, Continuities, and Change* (pp. 501–531). Brill.

Boonpitaksakul, W., Chitbanyong, K., Puangsin, B., Pisutpiched, S., & Khantayanuwong, S. (2019). [Natural Fibers Derived from Coi (Streblus asper Lour.) and their behavior in pulping and as paper](files/Boonpitaksakul et al. 2019.pdf). *BioResources* **14**(3), 6411–6420.

Helman-Ważny, A. (2014). “[A Survey of Tibetan Paper.](files/Helman-Wazny 2014.pdf)” In *The Archaeology of Tibetan Books* (pp. 179–200). Brill.  

Hudson, Z. (2019).  *[Bark of Dirca L.: Tensile properties, anatomy, and utility for handmade Asian-style bark paper.](Hudson 2019.pdf)*  Ph.D. thesis.  Iowa State University, Ames, IA, USA.

Jeanrenaud, J. P. (1984). *[Lokta (Daphne spp.) and craft paper-making in Nepal: A report on the current status, based on a literature review and preliminary field observations (May 1984-October 1984)](files/Jeanrenaud 1984.pdf)*.

Lochynska, M., & Oleszak, G. (2011). [Multi-use of the white mulberry (Morus alba L.).](files/Lochynska & Oleszak 2011.pdf) *Ecological Questions* **15**, 91–95.

Lopez-Binnqüist, C. L., Quintanar–Isaías, A., & Vander Meeren, M. (2012). [Mexican bark paper: Evidence of history of tree species used and their fiber characteristics.](files/Lopez-Binnquist et al. 2012) *Economic Botany* **66**(2), 138-148.

Mullock, H. (1995). [Xuan paper.](files/Mullock 1995.pdf) *The Paper Conservator* **19**(1), 23-30.

Peters, C. M., Rosenthal, J., & Urbina, T. (1987). [Otomi bark paper in Mexico: Commercialization of a pre-hispanic technology.](files/Peters et al. 1987.pdf) *Economic Botany* **41**(3), 423–432.

Rantoandro, G. (1983). [Contribution à la connaissance du « papier Antemoro » (Sud-est de Madagascar).](files/Rantoandro 1983.pdf) *Archipel* **26**(1), 86–104.

Schmidt, J., & Stavisky, N. (1983). [Uses of Thymelaea hirsuta (Mitnan) with emphasis on hand papermaking.](files/Schmidt & Stavisky 1983.pdf) *Economic Botany* **37**(3), 310–321.

Trier, J.  (1972).  *[Ancient paper of Nepal: results of ethno-technical field work on its manufacture, uses and history—with technical analyses of bast, paper and manuscripts.](files/Trier 1972.pdf)*  Copenhagen: Jutland Archaeological Society Publications.
</body>